### ISSUE TITLE
ImGui.Image causes a memory leak

### ISSUE THREAD

**Issue by AlubJ** [nommiin/ImGui_GM#9]
When using `ImGui.Image` it causes the memory to continue creeping up by a few fractions of a megabyte per second.

**Comment by nommiin** [comment]
Hiya, sorry for getting to this late but thanks for bringing it to my attention. But I've fixed the issue with this [commit](https://github.com/nommiin/ImGui_GM/commit/ab3e5118f5a6f7b7cd2e1e7e7234c9e130ae75aa). I had allocated UVs for images to the heap but forgot to free them at the end of the call!

I'll have a release up for ImGui_GM shortly that'll address this issue.

Thanks again!

**Comment by nommiin** [comment]
Fixed with the latest v1.0.13 release!
